### ISSUE TITLE
Make key quality of life updates to automated archiving

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl-archiver#418] opened 2024-09-03 14:15 UTC
The following challenges were observed in the September archive #412, and would speed the pace of monthly archiving:

```[tasklist]
- [x] adding a flag to delete drafts with no changes, and turning it on for the automated archive run. This will remove the step of manually deleting draft archives, which is done anyways to avoid having draft PRs cluttering Zenodo. This should not be the setting by default for local runs, but we can change the setting for the Github action. #419
- [x] Handle FERC taxonomy keys: sort the keys, to avoid changes in sorting creating new partition changes #419
- [x] https://github.com/catalyst-cooperative/pudl-archiver/issues/399
- [ ] Handle FERC taxonomy keys: ensure that null keys (e.g. for FERC 1996) don't get marked as updated files
- [ ] https://github.com/catalyst-cooperative/pudl-archiver/issues/473
- [ ] https://github.com/catalyst-cooperative/pudl-archiver/issues/471
```

**Comment by zschira** [comment] 2024-10-16 15:19
I've done some further research into the erroneous FERC XBRL archive updates and found the following:
1. he hashes of the zipfiles do differ 
2. The contents of the zipfiles are, however, identical and there are no longer partition changes, meaning #433 did fix the partition change error and the changes to the rssfeed file
3. The sizes of the zipfiles are identical
4. The timestamps of the files within the zips are identical

I'm still not really sure how/why the zips are differing. I tried creating a test to create 2 archives and check the hashes, but I'm unable to reproduce the error.

I'm going to try modifying the XBRL archivers to use our existing `add_to_archive_stable_hash` method and create two new archive versions for comparison. It does feel like directly comparing hashes of zipfiles is probably a bit fragile and a more in depth comparison might be better, but if `add_to_archive_stable_hash` solves the problem then it's probably good enough for now.

**Comment by jdangerx** [comment] 2024-11-04 20:36
Pulled out remaining pieces. closing

**Closed by jdangerx** 2024-11-04 20:36 UTC
Labels: automation
